name: Auto-bump Version on Merge

on:
  push:
    branches:
      - master

jobs:
  call-bump-workflow:
    uses: jasp-stats/jasp-actions/.github/workflows/auto-bump.yml@v1
    with:
      token_to_use: ${{ secrets.BUMP_TOKEN }}
    permissions:
      contents: write
